name: Display Lighthouse Report

on:
  push:
    branches:
      - main  # Ganti dengan branch Anda

jobs:
  display_lighthouse_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Lighthouse Report
      run: cat lighthouse_report/lighthouse.json  # Ganti dengan path file Lighthouse Anda
