name: Lighthouse CI

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Run Lighthouse
      run: npx lighthouse https://your-website-url.com --output=json --output-path=./lighthouse.json
    - name: Upload Lighthouse
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-report
        path: ./lighthouse.json
